Casep/Casep/Controllers/PostsController.cs
using System.Linq;
using System.Web.Mvc;
using Casep.Domain.Entities;
using Casep.Models;

namespace Casep.Controllers
{
    public class PostsController : CommonController
    {
        private const int PageSize = 5;

        public ActionResult Index(int? page, PostFilterType filterParametr = PostFilterType.AllNew)
        {

            if (!page.HasValue || page < 0)
                page = 1;

						var model = new PostsModel( Repository, Url );
						model.Init( page.Value, PageSize, filterParametr );						
            return View(model);
        }               

        public ActionResult Details(int id)
        {
            var model = new NewsDetailsModel
            {
                Post = Repository.SingleOrDefault<Post>(x => x.Id == id),
                Links = Repository.GetAll<Link>().ToList()
            };
            return View(model);
        }
    }

    public enum PostFilterType
    {
        AllNew = 0,
        LastNew = 1,
        Post2014 = 2,
        Post2013 = 3
    }
}

Casep/Casep/Views/Posts/Details.cshtml
@using Casep.Helper.Resources
@model Casep.Models.NewsDetailsModel

@{
    ViewBag.Title = Model.Post.Title;
}
<div class="clearfix"></div>
<div class="wrapper">
    <section>
        <h2>@ViewBag.Title</h2>
    </section>

    <div class="list-news">
        @Html.DisplayTextFor(m => m.Post.Description)

        <div class="clearfix"></div><hr />
        @Html.ActionLink(Messages.ВернутьсяНазад, "Index", "Posts")
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $("#headmenu-3").attr("class", "active");
    </script>
}

Casep/Casep/Views/Posts/Index.cshtml
@using Casep.Helper.Resources
@using PagedList.Mvc;
@model Casep.Models.PostsModel

@{
    ViewBag.Title = Messages.ПоследниеНовости;
}
<div class="clearfix"></div>

<div class="left-list-news">
    @Html.ActionLink(@Messages.Последние, "Index", new RouteValueDictionary { { "filterParametr", "1" } })
    <div class="clearfix"></div><hr/>
    @Html.ActionLink(@Messages.Архив, "Index", new { filterParametr = 0 })
    <div class="clearfix"></div><hr />
</div>    
        <div class="wrapper nn">
            <section>
                <h2>@ViewBag.Title</h2>
            </section>

            <ol class="list-news">
                @foreach (var m in Model.Posts)
                {
                    <li class="date">@m.Date.ToString("D")</li>
                    <li class="clearfix"></li>
                    <li class="_title">@Html.ActionLink(m.Title, "Details", "Posts", new { id = m.Id }, null)</li>
                    <li class="descr">@Html.DisplayTextFor(mm => m.MiniDescription)</li>
                    <li class="clearfix"><br /></li>
                }
                @if (Model.NeedPagging)
                {
                    @Html.PagedListPager(Model.Posts, page => Url.Action("Index", new {page}))
                }
            </ol>            
        </div>           

<div class="brick about" style="margin-left: 9px">
        <a href="@Url.Action("About", "Home")">
            <img src="~/Images/Casep/demo/casep_13.png" />
            <p class="casep">CASEP</p>
            <p class="present">@Messages.Презентация</p>
        </a>
    </div>

<div class="events">
    <div class="head-news" style="width: 230px;">@Messages.Мероприятия</div>
    <input type="text" class="eventCalendar" />

    @*Детали о событие (при навидение)*@
    <div class="eventDetails">
        <div id="eventDetails"></div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/DateTimePicker/jquery.datetimepicker.js"></script>
    <link href="~/Content/jquery.datetimepicker.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
        $("#headmenu-3").attr("class", "active");

        $('.eventCalendar').datetimepicker({
            format: 'd.m.Y',
            inline: true,
            timepicker: false,
            lang: '@Model.Activitys.SystemLanguage',
            eventLinks: '@Model.Activitys.JsonActivityCollection'
        });

    </script>
}