Casep/Casep.Admin/Controllers/ActivityController.cs
using System.Linq;
using System.Web.Mvc;
using Casep.Admin.Models;
using Casep.Domain.Entities;

namespace Casep.Admin.Controllers
{
    [Authorize]
    public class ActivityController : CommonController
    {
        public ActionResult Index()
        {
            var posts = Repository.GetAll<Activitys>();
            return View(posts);
        }

        public ActionResult Create()
        {
            return View(new EventModel());
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(EventModel activity)
        {
            if (!ModelState.IsValid) return View(activity);

            var dataModel = activity.ToDataObject(null);
            Repository.Add(dataModel);
            Repository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var activity = Repository.SingleOrDefault<Activitys>(x => x.Id == id);
            var viewModel = new EventModel();
            viewModel.InitModel(activity);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(EventModel activity, int id)
        {
            if (!ModelState.IsValid) return View("Create", activity);
            var page = Repository.SingleOrDefault<Activitys>(x => x.Id == id);
            activity.ToDataObject(page);
            //UpdateModel(editableActivity);
            Repository.SaveChanges();
            return RedirectToAction("Index");
        }          

        public ActionResult Delete(int id)
        {
            var activitys = Repository.SingleOrDefault<Activitys>(x => x.Id == id);

            if (activitys == null) return RedirectToAction("index");
            while (true)
            {
                if (!activitys.Documents.Any())
                    break;                
                Repository.Remove(activitys.Documents[0]);
            }
            Repository.Remove(activitys);
            Repository.SaveChanges();
            return RedirectToAction("index");
        }
        
        public ActionResult DeleteFile(int id)
        {
            var document = Repository.SingleOrDefault<Document>(x => x.Id == id);

            if (document == null) return RedirectToAction("index");
            Repository.Remove(document);
            Repository.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult DownloadFile(int id)
        {
            var file = Repository.SingleOrDefault<Document>(f => f.Id == id);
            return File(file.Binarys, file.MimeType, string.Format("document{0}", file.Extension));
        }

    }
}

Casep/Casep.Admin/Controllers/LinkController.cs
using System.Linq;
using System.Web.Mvc;
using Casep.Domain.Entities;

namespace Casep.Admin.Controllers
{
    public class LinkController : CommonController
    {
        public ActionResult Index()
        {
            var model = Repository.GetAll<Link>().ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            return View(new Link());
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Link link)
        {
            if (!ModelState.IsValid) return View(link);
            Repository.Add(link);
            Repository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var link = Repository.SingleOrDefault<Link>(x => x.Id == id);
            return View("Create", link);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Link link, int id)
        {
            if (!ModelState.IsValid) return View("Create", link);
            var page = Repository.SingleOrDefault<Link>(x => x.Id == id);
            UpdateModel(page);
            Repository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var link = Repository.SingleOrDefault<Link>(x => x.Id == id);

            if (link == null) return RedirectToAction("index");
            Repository.Remove(link);
            Repository.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

Casep/Casep.Admin/Controllers/PostController.cs
using System.Web.Mvc;
using Casep.Domain.Entities;

namespace Casep.Admin.Controllers
{
    [Authorize]
    public class PostController : CommonController
    {
        public ActionResult Index()
        {
            var posts = Repository.GetAll<Post>();
            return View(posts);
        }

        public ActionResult Create()
        {
            return View(new Post());
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Post post)
        {
            if (!ModelState.IsValid) return View(post);
            Repository.Add(post);
            Repository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var post = Repository.SingleOrDefault<Post>(x => x.Id == id);
            return View("Create", post);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Post post, int id)
        {
            if (!ModelState.IsValid) return View("Create", post);
            var page = Repository.SingleOrDefault<Post>(x => x.Id == id);
            UpdateModel(page);
            Repository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult TurnOnOff(int id, bool status)
        {
            var model = Repository.SingleOrDefault<Post>(x => x.Id == id);
            model.IsActive = status;
            UpdateModel(model);
            Repository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var model = Repository.SingleOrDefault<Post>(x => x.Id == id);
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            var news = Repository.SingleOrDefault<Post>(x => x.Id == id);

            if (news == null) return RedirectToAction("index");
            Repository.Remove(news);
            Repository.SaveChanges();
            return RedirectToAction("index");
        }

    }
}

Casep/Casep.Admin/Controllers/UserController.cs
using System.Linq;
using System.Web.Mvc;
using Casep.Domain.Entities;

namespace Casep.Admin.Controllers
{
    [Authorize]
    public class UserController : CommonController
    {
        public ActionResult Index()
        {
            var users = Repository.GetAll<User>().ToList();
            return View(users);
        }

        public ActionResult ActivateDiactivateProfile(int id, bool setActiv)
        {
            var dbUser = Repository.SingleOrDefault<User>(x => x.Id == id);
            dbUser.IsActive = setActiv;
            UpdateModel(dbUser);
            Repository.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult DeleteProfile(int id)
        {
            var user = Repository.SingleOrDefault<User>(x => x.Id == id);
            if (user == null) return RedirectToAction("index");
            Repository.Remove(user);
            Repository.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

Casep/Casep.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Administrative part</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        
        <!-- Start JavaScript -->
        <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
        <script src="/Scripts/jquery.js"></script>
        <script src="/Scripts/google-code-prettify/prettify.js"></script>
        <script src="/Scripts/bootstrap-transition.js"></script>
        <script src="/Scripts/bootstrap-alert.js"></script>
        <script src="/Scripts/bootstrap-modal.js"></script>
        <script src="/Scripts/bootstrap-dropdown.js"></script>
        <script src="/Scripts/bootstrap-scrollspy.js"></script>
        <script src="/Scripts/bootstrap-tab.js"></script>
        <script src="/Scripts/bootstrap-tooltip.js"></script>
        <script src="/Scripts/bootstrap-popover.js"></script>
        <script src="/Scripts/bootstrap-button.js"></script>
        <script src="/Scripts/bootstrap-collapse.js"></script>
        <script src="/Scripts/bootstrap-carousel.js"></script>
        <script src="/Scripts/bootstrap-typeahead.js"></script>
        <script src="/Scripts/bootstrap-affix.js"></script>
        <script src="/Scripts/application.js"></script>
        <script src="/Scripts/superfish.js" type="text/javascript"></script>
        <script src="/Scripts/custom.js" type="text/javascript"></script>
        <!-- End JavaScript -->

    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Casep", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Users", "Index", "User")</li>
                            <li>@Html.ActionLink("Events", "Index", "Activity")</li>
                            <li>@Html.ActionLink("Documents", "Index", "DocumentBase")</li>
                            <li>@Html.ActionLink("News", "Index", "Post")</li>
                            <li>@Html.ActionLink("Links", "Index", "Link")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Casep. All rights reserved.</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
@section Scripts {
    
}
</html>

Casep/Casep.Admin/Views/Shared/_createEditActivity.cshtml
@model Casep.Admin.Models.EventModel
 @Html.AntiForgeryToken()
    
    <fieldset class="form-horizontal">
        <legend>Create event</legend>
        <div class="tabbable" style="margin-bottom: 18px;">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab1" data-toggle="tab">Русский</a></li>
                <li><a href="#tab2" data-toggle="tab">English</a></li>
                <li><a href="#tab3" data-toggle="tab">Date start/end</a></li>
                <li><a href="#tab4" data-toggle="tab">Attach files</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab1">
                    <ol>
                        <li>
                            @Html.Label("Заголовок")
                            @Html.TextBoxFor(m => m.TitleRu)
                            @Html.ValidationMessageFor(m => m.TitleRu, null, new { @class = "help-inline" })
                        </li>                        
                        <li>
                            @Html.Label("Страна")
                            @Html.TextBoxFor(m => m.CountryRu)
                            @Html.ValidationMessageFor(m => m.CountryRu, null, new { @class = "help-inline" })
                        </li>
                        <li>
                            @Html.Label("Место проведения")
                            @Html.TextBoxFor(m => m.LocationRu)
                            @Html.ValidationMessageFor(m => m.LocationRu, null, new { @class = "help-inline" })
                        </li>                        
                    </ol>
                </div>
                <div class="tab-pane" id="tab2">
                    <ol>
                        <li>
                            @Html.Label("Title")
                            @Html.TextBoxFor(m => m.TitleEn)
                            @Html.ValidationMessageFor(m => m.TitleEn, null, new { @class = "help-inline" })
                        </li>                        
                        <li>
                            @Html.Label("Country ")
                            @Html.TextBoxFor(m => m.CountryEn)
                            @Html.ValidationMessageFor(m => m.CountryEn, null, new { @class = "help-inline" })
                        </li>
                        <li>
                            @Html.Label("Location ")
                            @Html.TextBoxFor(m => m.LocationEn)
                            @Html.ValidationMessageFor(m => m.LocationEn, null, new { @class = "help-inline" })
                        </li>                        
                    </ol>
                </div>
                <div class ="tab-pane" id="tab3">
                    <ol>
                        <li>
                            @Html.Label("Date start")
                            @Html.TextBoxFor(m => m.DateEventStart, null, new { @class = "calendarClassEn" })
                            @Html.ValidationMessageFor(m => m.DateEventStart, null, new { @class = "help-inline" })
                        </li>
                        <li>
                            @Html.Label("Date end")
                            @Html.TextBoxFor(m => m.DateEventEnd, null, new { @class = "calendarClassEn" })
                            @Html.ValidationMessageFor(m => m.DateEventEnd, null, new { @class = "help-inline" })
                        </li>                    
                    </ol>
                </div>
                <div class ="tab-pane" id="tab4">
                    <div id="ReadyDocuments">
                        @if (Model.Documents.Any())
                        {
                            <table class=" table table-striped">
                                <thead>
                                    <tr>
                                        <th>№</th>
                                        <th>Title</th>                                                                                                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    @{ var index = 1; }
                                    @foreach (var m in Model.Documents)
                                    {
                                        <tr>
                                            <td>@index</td>
                                            <td>@m.Title</td>                                                                                                                             
                                            <div class="btn-group">
                                                <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                                                <ul class="dropdown-menu">                                                    
                                                    <li>@Html.ActionLink("Delete", "DeleteFile", new { id = m.Id })</li>
                                                    <li>@Html.ActionLink("Download", "DownloadFile", new { id = m.Id })</li>
                                                </ul>
                                            </div>
                                        </tr>
                                        index++;
                                    }
                                </tbody>
                            </table>
                        }
                    </div>
                    <div id="fileContainer">                        
                    </div>
                    <button type="button" class="btn btn-primary" onclick="AddFileBlock();">+</button>
                </div>
            </div>
        </div>
        @**@
        <div class="bs-docs-example">
            <button type="submit" class="btn btn-primary">Save</button>
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn" })
        </div>
    </fieldset>

Casep/Casep.Admin/Views/Shared/_createEditDocumentBase.cshtml
@model Casep.Admin.Models.BaseDocumentModel
 @Html.AntiForgeryToken()
    
    <fieldset class="form-horizontal">
        <legend>Create event</legend>
        <div class="tabbable" style="margin-bottom: 18px;">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab1" data-toggle="tab">Description file</a></li>
                <li><a href="#tab2" data-toggle="tab">Attach</a></li>                
            </ul>
            
            <div class="tab-content">
                <div class="tab-pane active" id="tab1">
                    <ol>
                        <li>
                            @Html.Label("Описание(ru)")
                            @Html.TextBoxFor(m => m.DescriptionRu)
                            @Html.ValidationMessageFor(m => m.DescriptionRu, null, new { @class = "help-inline" })
                        </li>                        
                        <li>
                            @Html.Label("Описание(en)")
                            @Html.TextBoxFor(m => m.DescriptionEn)
                            @Html.ValidationMessageFor(m => m.DescriptionEn, null, new { @class = "help-inline" })
                        </li>                                        
                    </ol>
                </div>                
                <div class ="tab-pane" id="tab2">                    
                    <ol>                        
                        <li>
                            <label for="DocumentRu.File">File(ru)</label>
                            <input type="file" name="DocumentRu.File" data-val-required="Required the field File" data-val="true">
                        </li>
                    </ol>
                    <ol>                        
                        <li>
                            <label for="DocumentEn.File">File(en)</label>
                            <input type="file" name="DocumentEn.File" data-val-required="Required the field File" data-val="true">
                        </li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="bs-docs-example">
            <button type="submit" class="btn btn-primary">Save</button>
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn" })
        </div>
    </fieldset>