Casep/Casep.Admin/Controllers/DocumentBaseController.cs
using System.Linq;
using System.Web.Mvc;
using Casep.Admin.Models;
using Casep.Domain.Entities;

namespace Casep.Admin.Controllers
{
    [Authorize]
    public class DocumentBaseController : CommonController
    {
        
        public ActionResult Index()
        {
            var docoments = Repository.GetAll<BasesDocument>().ToList();
            return View(docoments);
        }

        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Create(BaseDocumentModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var baseDocument = model.ToDataObject(null);
            Repository.Add(baseDocument);
            Repository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var document = Repository.SingleOrDefault<BasesDocument>(x => x.Id == id);
            var baseDocument = new BaseDocumentModel();
            baseDocument.InitModel(document);
            return View(baseDocument);
        }
        
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(BaseDocumentModel model, int id)
        {
            if (!ModelState.IsValid) return View(model);
            var docModel = Repository.SingleOrDefault<BasesDocument>(x => x.Id == id);
            model.ToDataObject(docModel);
            Repository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var document = Repository.SingleOrDefault<BasesDocument>(x => x.Id == id);
            Repository.Remove(document);
            Repository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteFile(int id)
        {
            var document = Repository.SingleOrDefault<Document>(x => x.Id == id);

            if (document == null) return RedirectToAction("index");
            Repository.Remove(document);
            Repository.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult DownloadFile(int id, string lang)
        {
            var baseDocument = Repository.SingleOrDefault<BasesDocument>(f => f.Id == id);
            var file = lang == "ru" ? baseDocument.DocumentRu : baseDocument.DocumentEn;
            return File(file.Binarys, file.MimeType, string.Format("document{0}", file.Extension));
        }
    }
}

Casep/Casep.Admin/Views/DocumentBase/Create.cshtml
@model Casep.Admin.Models.BaseDocumentModel

@{
    ViewBag.Title = "Create document";
}
<section>
    <h1>@ViewBag.Title</h1>
</section>
<hr class="soften">

@using (Html.BeginForm("Create", "DocumentBase", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Partial("_createEditDocumentBase")
}

@section Scripts {    
     
    <link href="~/Content/jquery.datetimepicker.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/jquery.datetimepicker.js"></script>
    <script src="~/Scripts/PartialScript/CreateEditEvents.js"></script>
}

Casep/Casep.Admin/Views/DocumentBase/Edit.cshtml
@model Casep.Admin.Models.BaseDocumentModel

@{
    ViewBag.Title = "Create event";
}
<section>
    <h1>@ViewBag.Title</h1>
</section>
<hr class="soften">

@using (Html.BeginForm("Edit", "DocumentBase", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Partial("_createEditDocumentBase")
}

@section Scripts {    
     
    <link href="~/Content/jquery.datetimepicker.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/jquery.datetimepicker.js"></script>
    <script src="~/Scripts/PartialScript/CreateEditEvents.js"></script>
}

Casep/Casep.Admin/Views/DocumentBase/Index.cshtml
@model IEnumerable<Casep.Domain.Entities.BasesDocument>

@{
    ViewBag.Title = "Events";
}

<section>
    <h1>@ViewBag.Title</h1>
</section>
<hr class="soften">
@using (Html.BeginForm())
{
    @Html.ActionLink("Add document", "Create", null, new { @class = "btn btn-info white fl-r text-decor-none" })
    <table class=" table table-striped">
        <thead>
            <tr>
                <th>№</th>
                <th>File name (ru)</th>
                <th>File name (en)</th>                                
            </tr>
        </thead>
        <tbody>
            @{ var index = 1; }
            @foreach (var m in Model)
            {
                <tr>
                    <td>@index</td>
                    <td>
                        @Html.ActionLink(m.DescriptionRu, "DownloadFile", new {id = m.Id, lang = "ru"})
                    </td>
                    <td>
                        @Html.ActionLink(m.DescriptionEn, "DownloadFile", new {id = m.Id, lang = "en"})
                    </td>                                                                                                   
                    <td class="btn-group">
                        <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                        <ul class="dropdown-menu">                            
                            <li>@Html.ActionLink("Edit", "Edit", new { id = m.Id })</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Delete", "Delete", new { id = m.Id })</li>
                        </ul>
                    </td>
                </tr>
                index++;
            }
        </tbody>
    </table>
}
<hr class="soften">